version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Daugava1"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass Daugava1
    volumes: 
      - cachedata:/data

volumes:
  sqlserverdata:
    driver: local
  cachedata:  
    driver: local  